### ISSUE TITLE
server 

### ISSUE THREAD

**Issue by Jennifer0099** [payatu/Tiredful-API#7]
when I try it by Postman I got a message like this:
![2](https://user-images.githubusercontent.com/45819053/53830182-2aed3d80-3f82-11e9-9b77-1478de99a828.JPG)

**Comment by siddharthbezalwar** [comment]
Hi Jennifer,

Either the web server (django web server) is not running (there might be some error) , the system is not allowing connections on port 8000. If you are using docker then please check if it is exposing port 8000.
Also the "Authorization" header format is incorrect.

**Comment by Jennifer0099** [comment]
Thanks but I didn't use docker and I just copy the format from the website and the first authentication header is added by Postman.

**Comment by Jennifer0099** [comment]
like this:
![3](https://user-images.githubusercontent.com/45819053/53870225-1482c880-3ffa-11e9-8153-f8e7cb00ab3d.JPG)

**Comment by siddharthbezalwar** [comment]
If you are able to access the web application on http://localhost:8000/ then there is no issue with the web application and web services. 
I believe there is some settings issue in Postman you have configured.
Authorization header should be like:
" Authorization: Bearer sUWTCbWFK..." instead of "Authorization: Bearer <access_token:sUWTCbWFk..> "

**Comment by Jennifer0099** [comment]
do I need to write all of the token I got like: 
access_token:Z6xmCVPX9AE4GDkwD8aQS8R2xXHaq4
token_type:Bearer
expires_in:36000
refresh_token:BHRFXrS4bxaxKTC6iwCAuRQvyvJ44o
scope:read write groups

**Comment by Jennifer0099** [comment]
and I have another question that I want to use this API to test a tool which is for testing the vulnerability of RESTful API but the tool only accept Json format headers, so I need to convert everything to json format, and is it still okay ? can I still got authenticated?

**Comment by Jennifer0099** [comment]
and I am not very professional of Postman, so I didn't change any settings of it, and this is my another test result, which is using get method to test the information disclose vulnerability:
![1](https://user-images.githubusercontent.com/45819053/53873268-4565fc00-4000-11e9-8cb1-834a29c131d8.JPG)

**Comment by siddharthbezalwar** [comment]
Authorization header should be 
**Authorization: Bearer Z6xmCVPX9AE4GDkwD8aQS8R2xXHaq4**

And for 
_"and I have another question that I want to use this API to test a tool which is for testing the vulnerability of RESTful API but the tool only accept Json format headers, so I need to convert everything to json format, and is it still okay ? can I still got authenticated?_"

Yes you have to convert all headers to json format and you will be authenticated user as long as you are using valid bearer token in the request.

I am closing this issue as this is not an issue with the Tiredful API . If you have any more concerns please reach out over email siddharth[dot]bezalwar[at]gmail[dot]com
